### ISSUE TITLE
how can I test lstm model on data extracted by sensor kinect (3d skelton)

### ISSUE THREAD

**Issue by amalgmar12** [numenta/htmresearch#850]
Hi, 

I have my own dataset . I want to classify postures by continuous online leaning with kinetic sensor . Can you help me how can I process to adapt this algorithm to my own situation .Thank you in advance

**Comment by subutai** [comment]
Hi,
Do you mean HTM or LSTM? This github repository is primarily focused on HTM and we can't really help you on LSTM. 

For questions about HTM, please ask on our community forum site:  https://discourse.numenta.org

Thanks.
